
services:
  web:
    build: .
    image: secdev-seed:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=secdev-seed
      - DEBUG=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 3s
      retries: 5

    # сделал hardening S07-10 - Лимиты ресурсов контейнера (лайт)
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
